name: ALZ Zone-3 pipeline

on:
  workflow_dispatch:
    branches:
      - "alz-slim"
    paths:
      - 'infra-as-code/bicep/modules/resourceGroup/**'
      - 'infra-as-code/bicep/modules/spokeNetworking/**'

env:
  ManagementGroupPrefix: "alz"
  TopLevelManagementGroupDisplayName: "MyEdge Landing Zones"
  Location: "germanywestcentral"
  LoggingSubId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  LoggingResourceGroupName: "alz-centrallogging"
  HubNetworkSubId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  HubNetworkResourceGroupName: "Hub_Networking"
  RoleAssignmentManagementGroupId: "alz-platform"
  PrivateSpokeNetworkSubId: "6a4b4279-20aa-4245-8b88-64f9f491b9b2"
  PrivateSpokeNetworkResourceGroupName: "Private_LZ1_Networking"
  PublicSpokeNetworkSubId: "1e63056d-66f8-4d36-8454-b4375eb8578f"
  PublicSpokeNetworkResourceGroupName: "Public_LZ1_Networking"
  runNumber: ${{ github.run_number }}

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Private Spoke Networking Resource Group
        id: create_private_spoke_network_rg
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.PrivateSpokeNetworkSubId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          parameters: parResourceGroupName=${{ env.PrivateSpokeNetworkResourceGroupName }} parLocation=${{ env.Location }}
          deploymentName: create_spoke_network_rg-${{ env.runNumber }}
          failOnStdErr: false
      - name: Deploy Private Spoke Network
        id: create_private_spoke_network
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.PrivateSpokeNetworkSubId }}
          resourceGroupName: ${{ env.PrivateSpokeNetworkResourceGroupName }}
          template: infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
          parameters: infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json
          deploymentName: create_spoke_network-${{ env.runNumber }}
          failOnStdErr: false
      - name: Deploy Public Spoke Networking Resource Group
        id: create_public_spoke_network_rg
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.PublicSpokeNetworkSubId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          parameters: parResourceGroupName=${{ env.PublicSpokeNetworkResourceGroupName }} parLocation=${{ env.Location }}
          deploymentName: create_spoke_network_rg-${{ env.runNumber }}
          failOnStdErr: false
      - name: Deploy Public Spoke Network
        id: create_public_spoke_network
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.PublicSpokeNetworkSubId }}
          resourceGroupName: ${{ env.PublicSpokeNetworkResourceGroupName }}
          template: infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep
          parameters: infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json
          deploymentName: create_spoke_network-${{ env.runNumber }}
          failOnStdErr: false
